### ISSUE TITLE
issue onada

### ISSUE THREAD

**Issue by ceased-ebc** [arivarton/CurrencyStrength#1]
is this using the v20 api or a prior one as getting all sorts of parsing issues and not seeing any notes.

import datetime as dt
from pandas_datareader.oanda import get_oanda_currency_historical_rates
import numpy as np

window_size = 200
time = 2000

start = dt.datetime.today() - dt.timedelta(days=time)
end = dt.datetime.today()

base_currency = ["EUR", "GBP", "JPY", "USD"] #removed other currencies also added " instead of '

# Heavily inspired by this https://startpythonml.wordpress.com/2016/03/13/smoothed-moving-average-and-variations/
# and this https://www.dailyfx.com/forex/education/trading_tips/post_of_the_day/2011/06/15/How_to_Create_a_Trading_Edge_Know_the_Strong_and_the_Weak_Currencies.html
x = np.array([np.arange(0, time)])

weights = np.repeat(1.0, window_size) / window_size

for quote_currency in base_currency:
rating = 0
if base_currency != quote_currency:
df_rates = get_oanda_currency_historical_rates(
start, end,
quote_currency=quote_currency,
base_currency=base_currency
)
else:
pass
for base in base_currency:
y = np.array([df_rates[base + '/' + quote_currency].values])
yMA = np.convolve(y[0, :], weights, 'valid')
average_rate = yMA[len(yMA) - 1]
closing_rate = df_rates[base + '/' + quote_currency][time - 1]
if yMA[len(yMA) - 1] < df_rates[base + '/' + quote_currency][time - 1]:
rating -= 1
elif yMA[len(yMA) - 1] > df_rates[base + '/' + quote_currency][time - 1]:
rating += 1
elif yMA[len(yMA) - 1] == df_rates[base + '/' + quote_currency][time - 1]:
pass
else:
print('Something went wrong')
print('Final rating of ' + quote_currency + ': ' + str(rating))
----
Code pulls in data (guessing via CSV) from Onada, question is, is this an issue with Onada (old API) or an issue with the script?

**Comment by ceased-ebc** [comment]
Traceback (most recent call last):
File "cicero.py", line 26, in <module>
base_currency=base_currency
File "/usr/local/lib/python2.7/site-packages/pandas_datareader/oanda.py", line 46, in get_oanda_currency_historical_rates
usecols=usecols, engine='python')
File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 655, in parser_f
return _read(filepath_or_buffer, kwds)
File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 411, in _read
data = parser.read(nrows)
File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 1005, in read
ret = self._engine.read(nrows)
File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 2147, in read
content = self._get_lines(rows)
File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 2882, in _get_lines
row_num=self.pos + rows + 1)
File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 2630, in _next_iter_line
self._alert_malformed(msg, row_num)
File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 2589, in _alert_malformed
raise ParserError(msg)
pandas.errors.ParserError: ',' expected after '"'. Error could possibly be due to parsing errors in the skipped footer rows (the skipfooter keyword is only applied after Python's csv library has parsed all rows).
